@startuml
'https://plantuml.com/class-diagram

class Student extends Object{}
class Brigade  extends Object{}
class Faculty extends Object{}
class Object{}
class Year  extends Object{}
class Direction extends Object{}

Object --* Direction : GeneralTree<Object>

@enduml